version: 0.0 # CodeDeploy 버전
os: linux
files:
  - source: /
    destination: /home/ubuntu/good
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/stop.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/start.sh
      timeout: 180
      runas: ubuntu
    - location: scripts/health.sh
      timeout: 180
      runas: ubuntu
