version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/cicd
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 1000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 1000
      runas: ubuntu
  ValidateService:
    - location: scripts/health.sh
      timeout: 1000
      runas: ubuntu
