name: deploy to ec2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: ''corretto''

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean bootJar

      - name: Generate deployment package
        run: |
          mkdir -p before-deploy
          cp scripts/*.sh before-deploy/
          cp appspec.yml before-deploy/
          cp build/libs/*.jar before-deploy/
          cd before-deploy && zip -r before-deploy *
          cd ../ && mkdir -p deploy
          mv before-deploy/before-deploy.zip deploy/fruit-mall.zip
        shell: bash

      - name: Make zip file
        run: zip -r ./fruit-mall.zip .
        shell: bash

      - name: Deliver to AWS S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CICD_ACCESS_KEY  }}
          aws-secret-access-key: ${{ secrets.CICD_PRIVATE_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: aws s3 cp ./deploy/fruit-mall.zip s3://dkseo8484/jar-folder/

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --application-name cd-application-cicd \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name codeDeploy \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=fruit-mall-s3,bundleType=zip,key=dkseo8484/fruit-mall.zip \
          --region ap-northeast-2